### ISSUE TITLE
Make it possible to set icon size

### ISSUE THREAD

**Issue by fusion809** [The-Panacea-Projects/Gnomenu#102]
Hi,

I love this extension, but one thing that irritates me is how small the menu, view and apps icons are. I'd appreciate it if one could be allowed to set the icon size. 

Thanks for your time,
Brenton

**Comment by The-Panacea-Projects** [comment]
We have not looked into this before because of the desire to conform as much as possible with the default elements of the panel from which the icons' size are derived.

**Comment by fusion809** [comment]
Still leaves me with tiny icons, however. But I suppose if that was your intent there's little to be gained by me whining about it.
