### ISSUE TITLE
The GNO Menu does not work at all on GNOME 3.30.

### ISSUE THREAD

**Issue by Kerrung** [The-Panacea-Projects/Gnomenu#103]
Hi! Thank you for your the great work! But the GNO Menu does not work at all on GNOME 3.30.
I get an error message when I try to enable this extension.

![screenshot from 2018-09-12 03-43-17](https://user-images.githubusercontent.com/36989404/45391869-26cd0c80-b63e-11e8-97c8-1975591db050.png)

**Comment by The-Panacea-Projects** [comment]
@Kerrung I just uploaded a new version for Gnome 3.30 that is compatible with MosJs 60 (https://github.com/The-Panacea-Projects/Gnomenu/releases/tag/gno-menu.v28). Try it out and let me know if it works.

**Comment by Kerrung** [comment]
@The-Panacea-Projects Now it works very well! Thank you very much!
But this only works if I compile the git version from the source code, but, sadly, it still does not work if I try to install it from the extension page at: https://extensions.gnome.org/extension/608/gnomenu/
I still see that:
![screenshot from 2018-09-12 03-43-17](https://user-images.githubusercontent.com/36989404/45427943-90d6c780-b6b9-11e8-8cb8-df54fab0cda3.png)

**Comment by The-Panacea-Projects** [comment]
@Kerrung I uploaded the new version to the extension site also, but it's still under review (https://extensions.gnome.org/review/). They'll activate it after the review process.

**Comment by Kerrung** [comment]
@The-Panacea-Projects it's great! Thank you!
