### ISSUE TITLE
Logout puts computer to sleep on gnome 3.30

### ISSUE THREAD

**Issue by tnilzon** [The-Panacea-Projects/Gnomenu#106]
This is on gnome 3.30 and gno-menu 'master'-branch as of sept. 29

Gno-Menu button 'Logout User' logs out user, then suspends (puts to sleep) the computer.
Logout from gnome system menu (or by Ctrl+Alt+Del) works as expected.

**Comment by The-Panacea-Projects** [comment]
Fixed
