### ISSUE TITLE
Show favorites at start.

### ISSUE THREAD

**Issue by AnthLee1987** [The-Panacea-Projects/Gnomenu#11]
It would be mighty nice if there were an option to display favorites at start alongside the frequent and all options. Obviously there should also be a button with Frequent and All in the top of the menu to the left.

**Comment by The-Panacea-Projects** [comment]
Sorry about this late response(circumstances). I like both suggestions but as for additional buttons at the top left, cycling through favorites, frequent and all apps in turn using a single button is more likely to be the way it's implimented.

**Comment by The-Panacea-Projects** [comment]
This feature has been added as of version 17 for Gnome 3.18
