### ISSUE TITLE
Support needed for GNOME 3.32

### ISSUE THREAD

**Issue by Gallowwalker** [The-Panacea-Projects/Gnomenu#118]
This extension doesn't work with GNOME 3.32.

**Comment by FenrirTheGray** [comment]
Unfortunately Gno-Menu doesn't seem to work on Ubuntu 19.04 (3.32)

When I check out the LookingGlass I get this:
It throws the TypeError: "Shell.GenericContainer is not a constructor".

**Comment by Gallowwalker** [comment]
https://gitlab.gnome.org/GNOME/gnome-shell/merge_requests/361
https://gitlab.gnome.org/GNOME/gnome-shell/commit/bacfdbbb0338b94295c64093523bca7ba8d5c5ca

**Comment by xevilstar** [comment]
bump please update

**Comment by jjaone** [comment]
Still no working version for Gnome 3.32, bu  in Gnome-extensions page I found this [by Panacier]
"Apologies for the delay, there is a lot to get done and very little available time. If anyone can help with maintenance and updating it would be very much appreciated. We have uploaded a "3.32 compatible version to the home page "https://github.com/The-Panacea-Projects/Gnomenu"for those who would like early access, It's stable enough for daily use and feedback as to any bugs and so on would be appreciated."

Now, the quesion is:
- where is this alpha/pre-beta version of Gno-menu for 3.32
 - how is it supposed to be installed?

**Comment by The-Panacea-Projects** [comment]
On extension home page  " https://github.com/The-Panacea-Projects/Gnomenu "  download and extract  zip file. Do so via "Clone or download button" top right. Rename the extracted folder to " gnomenu@panacier.gmail.com " and move to your extensions folder.

Do remember to make sure " Gnome-menus " is first installed its a required dependency.

**Comment by jjaone** [comment]
Thanks, will try that 😉

**Comment by xevilstar** [comment]
> [gnomenu@panacier.gmail.com](mailto:gnomenu@panacier.gmail.com)

this works for me

**Comment by xevilstar** [comment]
REALLY nice to have it back
