### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by fa7ad** [The-Panacea-Projects/Gnomenu#12]
I really love this extension and been using it for a while now.
I just want to request one small setting change, that we can adjust the number of icons visible at once in grid mode.

**Comment by The-Panacea-Projects** [comment]
Late response sorry(circumstances) Our next move is to impliment pagination, thereafter we could look at an option to set the amount of visible icons for each page.

**Comment by fa7ad** [comment]
Thanks, that's good to know :laughing:
