### ISSUE TITLE
How to change menu bar size?

### ISSUE THREAD

**Issue by redscience** [The-Panacea-Projects/Gnomenu#128]
I used Kali Linux and I cannot see all of 14 menu subjects in one time, my middle mouse is corrupt and I have in trouble because i cannot go down correctly with my mouse , you know!
how can i change menu bar size to see all of 14 menu subjects in one time

**Comment by The-Panacea-Projects** [comment]
Try increasing number of columns  and or reducing icon size in menu settings.

**Comment by redscience** [comment]
I toke it before, 7 for columns and icon size to lowest content, but it is not enough for me, i can see only 9 menu in this condition

**Comment by The-Panacea-Projects** [comment]
In the extension's folder, locate the theme folder containing the style sheets and go to this line

.gnomenu-categories-workspaces-scrollbox {
    border-radius: 0;
    border: 0;
    height: 409px;
    padding: 0; }

Increase the height "409px" until sufficient for your mod.

**Comment by redscience** [comment]
you are the best man ! much appreciated
