### ISSUE TITLE
Gnomenu not compatible with Gnome 3.34.

### ISSUE THREAD

**Issue by Tuxman2** [The-Panacea-Projects/Gnomenu#129]
Hi,

your extension is fantastic (I'm using it on Gnome 3.32) but it is not compatible with Gnome 3.34 :(
Please, update your extension and make it compatible with Gnome 3.34.

In future releases, could you add a 'Parameters' button in the menu, and an option to Export and import settings like the 'dash-to-panel' extension did ?

Thanks. ;-)

**Comment by The-Panacea-Projects** [comment]
I Understand the need to keep things rolling, but with only one individual seeing to the necessary coding and that mostly when time allows does not make for easy going. If we had more contributors to assist  with fixes and such a lot more could be accomplished in a more timely fashion.

**Comment by asterlab** [comment]
bump

**Comment by asterlab** [comment]
is this project dead ?
