### ISSUE TITLE
French translation

### ISSUE THREAD

**Issue by Pierre-Thibault** [The-Panacea-Projects/Gnomenu#13]
I made a French translation. I am ready to create a pull request.

**Comment by The-Panacea-Projects** [comment]
@Pierre-Thibault .. I finally got some time to work on the project again. I'm ready to merge your translation file anytime you're ready.

**Comment by Pierre-Thibault** [comment]
Hello,

Happy to hear that.

I have a branch called french-translation having 'master 57fb72c Update PO
files for Japanese translation.' as parent.

How would you like to proceed from there?

2015-06-15 8:31 GMT-04:00 The Panacea Projects <notifications@github.com>:

> @Pierre-Thibault <https://github.com/Pierre-Thibault> .. I finally got
> some time to work on the project again. I'm ready to merge your translation
> file anytime you're ready.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/The-Panacea-Projects/Gnomenu/issues/13#issuecomment-112046133>
> .
>



-- 


A+

-------------
Pierre

**Comment by The-Panacea-Projects** [comment]
You can open a pull request or just email the PO file to me (panacier@gmail.com).

**Comment by Pierre-Thibault** [comment]
Cannot create a pull request beacause I don't have the right to push my
branch.

2015-06-16 14:01 GMT-04:00 The Panacea Projects <notifications@github.com>:

> You can open a pull request or just email the PO file to me (
> panacier@gmail.com).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/The-Panacea-Projects/Gnomenu/issues/13#issuecomment-112515363>
> .
>



-- 


A+

-------------
Pierre

**Comment by The-Panacea-Projects** [comment]
Just email the PO file to panacier@gmail.com. I'll merge it into the master branch on my end.

**Comment by The-Panacea-Projects** [comment]
French translation has been merged in 428db098f24265bec5d5cc3cbc07975df60282c4
