### ISSUE TITLE
GnoMenu not looking as it should

### ISSUE THREAD

**Issue by tirafesi** [The-Panacea-Projects/Gnomenu#130]
How can I change the color of GnoMenu? I ran the [GNOME Layout Manager](https://github.com/vmavromatis/gnome-layout-manager) script, but for some reason the menu is gray instead of black - which looks awful.

How it should look like: https://i.imgur.com/0Dk4HOu.png

How it looks: https://i.imgur.com/B3Jvhaj.png

How can I fix this?

**Comment by The-Panacea-Projects** [comment]
It assumes the colors of the default popup menus. You could also look at making changes to the theme file in the extensions folder.
