### ISSUE TITLE
shortcut key should toggle appearance not just show menu

### ISSUE THREAD

**Issue by muhammedabuali** [The-Panacea-Projects/Gnomenu#18]
when I press the shortcut key 
if the menu is not there it shows 
but if it is visible nothing happens .
I think it should be hidden if ipress it agin just like the overview

**Comment by The-Panacea-Projects** [comment]
Thanks for pointing that out and you are right. This will be done soon.

**Comment by The-Panacea-Projects** [comment]
Feature added in version 17 for Gnome 3.18
