### ISSUE TITLE
Dutch translation

### ISSUE THREAD

**Issue by Vistaus** [The-Panacea-Projects/Gnomenu#19]
Hello,

thanks for this wonderful extension! I've translated it to Dutch (based on the current Git master branch) :)
https://onedrive.live.com/redir?resid=7a03150cc9bee130!22511&authkey=!ANrpxG2_mzZi-Hs&ithint=file%2cpo

**Comment by The-Panacea-Projects** [comment]
Thanks. I'll merge this as soon as I can.

**Comment by The-Panacea-Projects** [comment]
@Vistaus, I'm not able to access your translation file. Would you re-share please?

**Comment by The-Panacea-Projects** [comment]
Still waiting.

**Comment by Vistaus** [comment]
Seems like Microsoft removed it from my OneDrive, I'll send them an e-mail to ask why and if they can put it back. (I lost my local backup :( )

**Comment by The-Panacea-Projects** [comment]
Appreciated.
