### ISSUE TITLE
Couple of bug reports and suggestions

### ISSUE THREAD

**Issue by kminh** [The-Panacea-Projects/Gnomenu#22]
Hello, thank you guys for this awesome extension. Just want to report a few bugs and suggest some improvements:

**Bugs**
- If I set the icon size for List view of application to be larger than 24, the icon is distorted.
- The text and icon in the search bar is invisible.
- The Logout and Lock power buttons look stretched.
I'm using Numix Frost gnome shell theme: https://github.com/lots0logs/Numix-Frost . This theme has some compatibility issues with gnome shell 3.16 but not sure if that's the reason why I'm seeing these bugs.

Below is the image describing the bugs:

![screenshot from 2015-07-23 12-14-22](https://cloud.githubusercontent.com/assets/6402124/8844300/c0996e0a-313d-11e5-9b5c-e64d0c44f2d6.png)

**Suggestions**
- Add the option to disable hovering effect on panel menu, right now it is too sensitive and sometimes the menu is shown unintentionally.
- Add the option to disable the bold font of applications and categories. IMO, the only things that should be bold by default is the group labels and selected application's label.
- Add the option to add the down arrow to the end of the menu so it looks consistent.
- Make the menu button shortcut key a toggle key, i.e. pressing it should toggle the menu, not just show it.

Thanks for consideration.

**Comment by The-Panacea-Projects** [comment]
We are currently looking into the issues and should be able to upload a fix for the theme related ones shortly. The option to disable hover effect is already in configurations, we will also be implementing pressure barrier to mitigate against accidental toggles and as you have indicated modify the shortcut key to toggle menu. As for the bold labels and drop down arrow we somewhat agree, though the labels will likely be address in the theme file as oppose to adding an option.

**Comment by kminh** [comment]
Hmm you mean the "Disable Menu button hot spot"? It is checked but still when I hover the menu it is shown.

Great to hear that you guys are working on it. I can help testing whenever the fixes are available, just tell me which branch to clone.

Thank you.

**Comment by The-Panacea-Projects** [comment]
I see, did you restart the shell? I have since check and it's working on Fedora 23. There is a lot we would like to get accomplish but very little spare time to code, if you are able to or are aware of anyone who could lay a few lines of code to help move things along at a quicker pace this would be well appreciated.

**Comment by kminh** [comment]
Ahh restarted the shell and now hovering is disabled.

This is a very useful extension so I hope it gets better eventually, but no need to rush. I hope this one won't get abandoned like most extensions out there... I will keep my eyes on this one as well.

Thanks again.

**Comment by rik-shaw** [comment]
Regarding height of List View for applications, it is hard coded in the css files, it isn't based on icon size.  So if you want to manually change it, then change the height value of the gnomenu-application-list-button element in the relevant gnomenu.css file. (gnomenu.css for "large menu", gnomenu-m.css for "medium menu", gnomenu-s.css for "small menu")

The better fix is to have the height of the application elements (for List view and also Grid view) dynamically based on the selected icon size.

**Comment by The-Panacea-Projects** [comment]
Closing as all of these quirks have been resolved or features added.
