### ISSUE TITLE
Minor: Use shortcut that opens menu to close it

### ISSUE THREAD

**Issue by krlmlr** [The-Panacea-Projects/Gnomenu#23]
I might hit F2, realizing a split-second later that this is not what I wanted to do. Would be great if F2 also closed the open menu.

**Comment by The-Panacea-Projects** [comment]
Yes this will be address in the next release, using the Esc button for the time being might help.

**Comment by rik-shaw** [comment]
+1 on this request: good to know it may make the next version.

**Comment by The-Panacea-Projects** [comment]
It's already been coded in for next release.
