### ISSUE TITLE
More immediate feedback

### ISSUE THREAD

**Issue by krlmlr** [The-Panacea-Projects/Gnomenu#24]
It takes some time to display the menu after F2 has been pressed. It seems that the CPU (gnome-shell process) is quite busy when repeatedly opening and closing the menu -- perhaps populating the lists takes some time.

My primary use case is to open the menu, then type the name of the application I want to start. In the vast majority of cases, I don't care about the categories or the "most recently used applications".

Is it possible to present an empty menu right away, and filling it later (perhaps asynchronously), or to otherwise accelerate the opening process?

**Comment by The-Panacea-Projects** [comment]
We are currently working on the option to collapse categories and should be able to offer a blank icon grid as well.

**Comment by The-Panacea-Projects** [comment]
Category collapse and blank icon grid have been added in version 17 for Gnome 3.18
