### ISSUE TITLE
Recommendation: reduce AppGrid Columns to 3 

### ISSUE THREAD

**Issue by rik-shaw** [The-Panacea-Projects/Gnomenu#26]
With AppGrid Columns set at 5 it really chops a lot of Application names in an unusable way, in my opinion.  For example, all LibreOffice apps are listed as "LibreOffi..."  Yes, at the bottom there is the full name and description (great feature BTW), but it would be better, in my opinion, to reduce the number of columns to 3 and then increase the width of the gnomenu-application-grid-button and gnomenu-application-grid-button-label in the css files.

**Comment by The-Panacea-Projects** [comment]
We could see it going to four but three seems a bit much, this would mean giving up a lot of real-estate to simply facilitate full names in grid view and most apps are easily identified by their icons.

**Comment by The-Panacea-Projects** [comment]
BTW... if you can help with coding a few changes we could definitely use the help.

**Comment by rik-shaw** [comment]
@The-Panacea-Projects Yes I may be able to help with some patches.  I'll contact you directly.

**Comment by The-Panacea-Projects** [comment]
Grid columns can now be set through the preferences dialog as of version 17 for Gnome 3.18
