### ISSUE TITLE
Searchbar: look at "exec" and "keywords" desktop fields

### ISSUE THREAD

**Issue by rik-shaw** [The-Panacea-Projects/Gnomenu#27]
Currently Gno-Menu doesn't seem to find apps that don't have their display name match their executable name.  An example would be "Alacarte", which is only found by typing "Main Menu".  So, it would be good if the search could look at the "exec" line.

Secondly, it would be great if Gno-Menu looked at the "Keywords" field as well.  The whole idea behind the "Keywords" entry is to give a place for additional metadata to facilitate searching.  Here is the Gnome reference document on the Desktop Entry Specification: https://developer.gnome.org/desktop-entry-spec/

**Comment by krlmlr** [comment]
Same as #32.

**Comment by The-Panacea-Projects** [comment]
Issue fixed with commit 2d622cb6bdf17a22a0a10c7ea6a0ea0936b312e1

**Comment by rik-shaw** [comment]
Thanks to @jstnlth for the fix.  This will allow us to modify the keywords for gnome-control-center in order to have it be "found" when a user types for a specific module such as "mouse", "display", "keyboard", etc.  Additionally, now a user typing "nautilus" will have it returned.
