### ISSUE TITLE
Keyboard Navigation: Ability to change focus to Categories or Favorites?

### ISSUE THREAD

**Issue by rik-shaw** [The-Panacea-Projects/Gnomenu#28]
It would be very nice to be able to use a "keyboard only" for Gnomenu use: Defaulting keyboard focus to the App Grid is fine, but it would be nice if a "tab" would toggle focus to the "Categories", and maybe a second "tab" would get over to "Favorites", then a third "tab" would get back to App Grid focus.  Not sure if this is possible or not, but would be a "nice to have".

**Comment by The-Panacea-Projects** [comment]
Yes  this only seems natural, we will look into it.
