### ISSUE TITLE
"Excel" and "Nautilus" not found

### ISSUE THREAD

**Issue by krlmlr** [The-Panacea-Projects/Gnomenu#32]
When I search for "Excel" or "Nautilus", the overview finds LibreOffice Calc and Nautilus; GnoMenu doesn't. Aliases?

**Comment by rik-shaw** [comment]
This is because Gnomenu seems to only look at the "Display Name" and "Comments" fields in desktop files.  I hope it can be expanded to look at the Exec and Keywords fields, which would then return the results you are desiring.  See this bug report: #27

**Comment by The-Panacea-Projects** [comment]
Issue fixed with commit 2d622cb6bdf17a22a0a10c7ea6a0ea0936b312e1
