### ISSUE TITLE
Update to Gnome 3.18

### ISSUE THREAD

**Issue by SalahAdDin** [The-Panacea-Projects/Gnomenu#33]
We have a new gnome versiona at last, but it's not compatible with 3.18. Can you update this extrension please?

**Comment by The-Panacea-Projects** [comment]
So sorry for the delay. A new version is ready, we are currently cleaning up the code a bit before uploading.

**Comment by SalahAdDin** [comment]
Ok, thanks, i copy this repository in the extension folder for now. :D :+1:

**Comment by The-Panacea-Projects** [comment]
Okay but that's an earlier version, the current version has been emailed.

**Comment by SalahAdDin** [comment]
Thanks :+1:

**Comment by JuanMDSousa** [comment]
Hi :D Big fan of your project. Can u send me the last version? I got a bug of (If you want to search Firefox bookmarks...) And I already installed the libs ><

OpenSUSE Tumbleweed.

Thanks!

**Comment by The-Panacea-Projects** [comment]
Well yes and its good to hear you find Gnomenu useful. Please provide an email address and kindly let us know if the bug persists .

**Comment by JuanMDSousa** [comment]
Hi :D juanmdsousa@gmail.com

Thanks a lot.

**Comment by The-Panacea-Projects** [comment]
Closing as new version is out.
