### ISSUE TITLE
Gno menu error

### ISSUE THREAD

**Issue by LionSec** [The-Panacea-Projects/Gnomenu#37]
Hello , thank you for this extension :) . 

I have a problem , yesterday suddenly , i had an error . After refreshing gnome shell (with alt + f2), Gno-menu disapeared , and in firefox i saw this error (http://i.imgur.com/a5fGDJf.png).

I am using ubuntu gnome 15.10 . with gnome shell 3.16
Please help me or give me an old versión of gno menu if you can. Regards

**Comment by LionSec** [comment]
I have resolved the problem . I have have this problem when i add a category in the menu , using alacarte . So , i resolved the my problem removing the last category i had added. Regards

**Comment by The-Panacea-Projects** [comment]
Real pleased to hear this, as given our time constraints most fixes are done on current version. Hopefully we will have fixed this by the time you migrate to 3.18.
