### ISSUE TITLE
Compatibily with 3.20

### ISSUE THREAD

**Issue by Ste74** [The-Panacea-Projects/Gnomenu#45]
Please updtate

**Comment by The-Panacea-Projects** [comment]
Will do shortly just making a few adjustments for official release, changing the metadata to 3.20 will have it working again for the moment.

**Comment by Ste74** [comment]
Thank you for reply , you mean here ?
https://github.com/The-Panacea-Projects/Gnomenu/blob/master/metadata.json#L5

**Comment by The-Panacea-Projects** [comment]
Yes, please change to "3.20" and all should be fine.

**Comment by Ste74** [comment]
Ok thank you again :)
