### ISSUE TITLE
Change shortcut to launch gnomenu

### ISSUE THREAD

**Issue by Ste74** [The-Panacea-Projects/Gnomenu#47]
Hi , i have create a pkg for this extension to install into Manjaro linuxas default extension .. Is possible change the default <F2> shortcut ? I have try to override via dconf-editor but the schemas not work after fresh install ( run the first itme the iso ) . The key appear after modified into gnomenu ... is only possible via modify the xml schemas ?
`   <key type="as" name="panel-menu-keyboard-accelerator">
        <default><![CDATA[['F2']]]></default>
      <summary>Disable the menu button keyboard shortcut</summary>
      <description>Disable the menu button keyboard shortcut</description>
</key>`

**Comment by The-Panacea-Projects** [comment]
@Ste74, You should be able to modify the schema file and set the default keyboard shortcut. Just make sure it doesn't conflict with any of the system shortcuts.

**Comment by Ste74** [comment]
Done , thank you : override your original schemas :wink:
