### ISSUE TITLE
Conflict between Gnomenu and frippery move clock

### ISSUE THREAD

**Issue by eXk0n** [The-Panacea-Projects/Gnomenu#49]
Enabeling Gnomenu or restaring the gnome shell causes the clock to be moved to its original place in the middle. 
Toggeling frippery move clock on and off moves clock back to the ntended location. 
This issue also reproducable on a second machine.

I made a short video illustrating the problem (sorry for the flickering, seems to be a bug in OBS):
<blockquote class="imgur-embed-pub" lang="en" data-id="OCyV8SD"><a href="//imgur.com/OCyV8SD">Gnomenu issue</a></blockquote><script async src="//s.imgur.com/min/embed.js" charset="utf-8"></script>

Thank you in advance for looking at this issue

**Comment by rmyorston** [comment]
I'm the author of Frippery Move Clock.

I can restore the correct behaviour by commenting out the two calls to ```Main.panel._updatePanel()``` in Gnomenu. It appears that ```_updatePanel``` is only intended to be called when the session mode changes, not when changes are made to the contents of the panel.

**Comment by The-Panacea-Projects** [comment]
@rmyorston, thanks for troubleshooting the issue. I'll make the changes to the code as soon as I get some coding time.
