### ISSUE TITLE
Allow adding/removing of favorites

### ISSUE THREAD

**Issue by Queuecumber** [The-Panacea-Projects/Gnomenu#5]
Hi, enhancement idea:

Allow adding/removing of apps to the favorites list. I've seen this implemented in other apps using a right click, a submenu would also work.

**Comment by rik-shaw** [comment]
+1 on this feature request.

**Comment by mikolajzieba** [comment]
Is adding favorites already working?

**Comment by The-Panacea-Projects** [comment]
No, still on the to-do list. A patch would be welcome if possible.
