### ISSUE TITLE
how change icon 

### ISSUE THREAD

**Issue by tjw0lf** [The-Panacea-Projects/Gnomenu#50]
how can change the icon in gno-menu. to something else besides Foot

Please help thank you

**Comment by The-Panacea-Projects** [comment]
Sorry for the delayed response.

The Menu button icon uses the 'start-here-symbolic' icon located in the /usr/share/icons/Adwaita/scalable folder (or whichever theme you're using). You can change it, though, to any other svg icon in that theme folder. Just open up the extension preferences and find the option to 'Use icon with Menu button'. Replace the 'start-here-symbolic' with the name of the svg icon you would rather use.
