### ISSUE TITLE
Starting application on touch screen does not work

### ISSUE THREAD

**Issue by evfool** [The-Panacea-Projects/Gnomenu#52]
Hi,

On a touch-enabled laptop, applications can not be started from gnomenu using a touch, touch is handled as mouse over. The only way to start an application is to type a filter text, and press enter, which starts the first application.

**Comment by The-Panacea-Projects** [comment]
Could you try the latest from the master branch. I just added touch support but I have no way of testing it.

**Comment by evfool** [comment]
wow, that was fast :) I have just tested it, category buttons work now, but AppGridButtons still can not start the applications. I'm not sure why is that, the relevant commits look ok, touch-event is handled for AppGridButtons too, as far as I saw from the diff. 
No worries however, I know it's not easy to get touch support right without testing, I'll check the code and possibly come up with a pull request with working touch support later.

**Comment by evfool** [comment]
Closing this, as it does work now. I have experenced strange extension reloading issues with other extensions too, it might have been the same issue.
