### ISSUE TITLE
Override apps function in the panel

### ISSUE THREAD

**Issue by Ste74** [The-Panacea-Projects/Gnomenu#58]
Hi there , i have override this key in manjaro gnome community iso  
https://github.com/The-Panacea-Projects/Gnomenu/blob/master/schemas/org.gnome.shell.extensions.gnomenu.gschema.xml#L57
but when build the pkgs and install the button is always present .. i missed other keys ?
i need to default not see this key .

Thank you 😄

**Comment by The-Panacea-Projects** [comment]
The key might be getting reset after installing Gnomenu. There's a compiled 'gschemas.compiled' file in the extension schemas folder that already uses the default keys. Try deleting it and rebuilding the schema file using glib-compile-schemas.

**Comment by Ste74** [comment]
Yep this work .. thank you 😉
