### ISSUE TITLE
[Feature Request] Pressing Enter in search box launches first result

### ISSUE THREAD

**Issue by jderose9** [The-Panacea-Projects/Gnomenu#59]
It would be great if pressing enter/return in the search box would launch the first item in the results. This is the behavior I am accustomed to from XFCE Whisker Menu, KDE Plasma app menu, Windows start menu, etc.

**Comment by jderose9** [comment]
I created a pull request for my implementation: https://github.com/The-Panacea-Projects/Gnomenu/pull/60

**Comment by The-Panacea-Projects** [comment]
Thanks, implemented/merged.
