### ISSUE TITLE
Unable to disable F2 shortcut

### ISSUE THREAD

**Issue by milankni** [The-Panacea-Projects/Gnomenu#69]
I use Gnomenu with Dast to panel extension. Pressing F2 opens "Menu" and there is no setting in preferences of Gnomenu to disable such a behaviour.

This bug steals the key bindings from other apps like gnome-terminal (F2 is save in Midnight Commander editor and others).

**Comment by The-Panacea-Projects** [comment]
Actually it can be disabled or changed in preferences, its the last 
option under Panel Settings.

**Comment by milankni** [comment]
You're right, I must have overlooked it before. Thanks.
