### ISSUE TITLE
Option to remove dropdown arrow

### ISSUE THREAD

**Issue by caseca** [The-Panacea-Projects/Gnomenu#82]
Or option to remove the arrow or respect the plugin remove dropdown arrows

**Comment by thunderschnozzle** [comment]
I second that. It'd be nice to remove that arrow from the Menu button

**Comment by webmastak** [comment]
On the gnome 3.28 remove dropdown arrows please.

**Comment by The-Panacea-Projects** [comment]
@caseca, @thunderschnozzle, @webmastak .. The latest master branch commits have added an option to remove the menu dropdown arrows.
