### ISSUE TITLE
[Bug] After searched an application name, can't run the application with enter key on keyboard

### ISSUE THREAD

**Issue by ceyhunnabiyev** [The-Panacea-Projects/Gnomenu#87]
For example, I searched vlc on search bar, it found vlc, but vlc can't be launched with enter key, only works with mouseclick.

**Comment by The-Panacea-Projects** [comment]
I'm looking into the issue.

**Comment by The-Panacea-Projects** [comment]
@ceyhunnabiyev Please test the latest master branch to verify this bug is fixed. Thanks.

**Comment by ceyhunnabiyev** [comment]
@The-Panacea-Projects , Sorry for late answer. It has been fixed. Thank you.
