### ISSUE TITLE
Application are not shown on startup

### ISSUE THREAD

**Issue by K5HV** [The-Panacea-Projects/Gnomenu#91]
Hi,
no application are show when regardless what option in Preferences is set.

![screenshot from 2018-05-14 11-19-09](https://user-images.githubusercontent.com/24753934/40001632-ebe60062-578e-11e8-9c27-c1b0235bacf1.png)

**Comment by K5HV** [comment]
I've upgraded Gnomenu to v25, issue still exists.
OS: Arch Linux
Pkg version: gnome-shell-extension-gnomenu 25-1

**Comment by SunnySoldier357** [comment]
I have a similar problem and but I am running Ubuntu 18.04 and my gnome version is 3.28.1.

**Comment by ceyhunnabiyev** [comment]
The problem also occurs on me. Screenshot from Gnome-logs:
![screenshot from 2018-05-23 01-11-32](https://user-images.githubusercontent.com/5506156/40390450-58d7564c-5e26-11e8-8edc-92c2f2597192.png)

**Comment by webmastak** [comment]
Install the Arc Menu and everything will work.
https://extensions.gnome.org/extension/1228/arc-menu

I modified it a bit for myself and it became much more convenient.

![](https://i.imgur.com/P2CxnSx.png)

**Comment by K5HV** [comment]
I've used latest version from master (21c562357ccd24eb973a678b96ed8c933b3fba7f).
It didn't helped. There is no application visible on startup.

**Comment by The-Panacea-Projects** [comment]
Code is being adjusted, we will upload as soon as we have a fix.

**Comment by The-Panacea-Projects** [comment]
The necessary fixes have been merged and uploaded to master here https://github.com/The-Panacea-Projects/Gnomenu. This should resolve issue #88, #91, and #92. To install click the green Clone or download button to the right and choose Download ZIP, then rename extracted folder and place into your extensions folder.

**Comment by K5HV** [comment]
Oh yeah, it seems that problem has been fixed now.
Thank you!

**Comment by CmndrBodang** [comment]
Hey, Noob here, how do I install this awesome looking menu? Ive downloaded and extracted it. Now Im lost lol

**Comment by auipga** [comment]
@CmndrBodang 
> rename extracted folder and use to replace the one in your extensions folder.

`~/.local/share/gnome-shell/extensions`
