### ISSUE TITLE
Weird alignment of menu items

### ISSUE THREAD

**Issue by prakhar1912** [The-Panacea-Projects/Gnomenu#92]
After a system update, the menu items on the left have a weird margin on the left
![whatsapp image 2018-05-22 at 11 09 13 am](https://user-images.githubusercontent.com/20063271/40344074-b32ad2ca-5db0-11e8-8c6d-4cc4f7f91590.jpeg)

**Comment by ceyhunnabiyev** [comment]
Also occurs in my Manjaro Gnome with latest version.

**Comment by prakhar1912** [comment]
Also, right clicking on that space is removing the menu items altogether. The menu items come back on restarting Gnome

**Comment by webmastak** [comment]
Install the Arc Menu and everything will work.
https://extensions.gnome.org/extension/1228/arc-menu
I modified it a bit for myself and it became much more convenient.
https://i.imgur.com/P2CxnSx.png

**Comment by prakhar1912** [comment]
@webmastak Thanks! This works fine. I will leave the issue open so that the develop has a chance to fix it.

**Comment by prakhar1912** [comment]
Yes, the latest update fixed it, and made it even better. Thanks!
