### ISSUE TITLE
GUI corrections

### ISSUE THREAD

**Issue by rypz79** [The-Panacea-Projects/Gnomenu#94]
Hi,

Few issues:

1. There is an empty space between the places icons and the applications categories sub-menus (red rectangle)
2. The place description should be aligned to the button icons in the buttom (green rect)
3. There should be an option to increase/decrease the icon size of the Menu button (blue rect) and the option to bind it to a key other than F2.

Nice extension
I hope you can address these issues
Thanks
![screenshot from 2018-05-31 15-45-24](https://user-images.githubusercontent.com/28814757/40783565-865a24a2-64eb-11e8-90c9-e4cc58aa78d0.png)

**Comment by The-Panacea-Projects** [comment]
What gnome shell theme are you using? Have you tested with Adwaita?

**Comment by rypz79** [comment]
I'm using the latest - v3.28.1
I've now installed adwaita-icon-theme-full package

The red rect is fixed there is no more empty space.
In the green rect I see that the alignment is not fixed to the button because there is a line space for the app description one you hover on one.

I still cannot change the Menu icon size or bind it to other key 

Thanks

**Comment by The-Panacea-Projects** [comment]
Will you please try the latest version from extension's home page.

**Comment by The-Panacea-Projects** [comment]
Instruction are here https://extensions.gnome.org/extension/608/gnomenu/

**Comment by rypz79** [comment]
Alright. Updated it. Looks very good.
Still I cannot change the size of the start here icon nor can I bind it to a key other then F2
Thanks!

**Comment by rypz79** [comment]
Is there a way to increase the start-here-symbol and remove the arrow next to it ?
![111](https://user-images.githubusercontent.com/28814757/41226119-2f05a53c-6d79-11e8-9b27-ed893587625e.png)

Thanks
