### ISSUE TITLE
Can't Search and hit Enter to open app.

### ISSUE THREAD

**Issue by Insasse** [The-Panacea-Projects/Gnomenu#97]
I upgraded my gno-menu yesterday on Ubuntu 18.04.
Before that I can hit F2 type my app and than hit enter and its open.
But now I have to click it with my mouse which slows me down.

![gno-menu](https://user-images.githubusercontent.com/13465328/41400495-9a18b2e2-6fbd-11e8-8a3c-89bf84e1db90.gif)

**Comment by Insasse** [comment]
I used the latest release how can I install this exension from master?

**Comment by The-Panacea-Projects** [comment]
Extract the zip file, rename to "gnomenu@panacier.gmail.com".  Use to replace the one in your extensions folder.

**Comment by Insasse** [comment]
@The-Panacea-Projects  yeah that worked like a charm and looks even better as before, hope next release will come soon :)
